package com.example.administrator.mobilepacsviewer.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.administrator.mobilepacsviewer.model.SearchTemplateEntity;
import com.example.administrator.mobilepacsviewer.model.QueryInfoRet;
import com.example.administrator.mobilepacsviewer.model.DepartmentEntity;
import com.example.administrator.mobilepacsviewer.model.OrganizationEntity;
import com.example.administrator.mobilepacsviewer.model.IPAddressEntity;

import com.example.administrator.mobilepacsviewer.model.SearchTemplateEntityDao;
import com.example.administrator.mobilepacsviewer.model.QueryInfoRetDao;
import com.example.administrator.mobilepacsviewer.model.DepartmentEntityDao;
import com.example.administrator.mobilepacsviewer.model.OrganizationEntityDao;
import com.example.administrator.mobilepacsviewer.model.IPAddressEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchTemplateEntityDaoConfig;
    private final DaoConfig queryInfoRetDaoConfig;
    private final DaoConfig departmentEntityDaoConfig;
    private final DaoConfig organizationEntityDaoConfig;
    private final DaoConfig iPAddressEntityDaoConfig;

    private final SearchTemplateEntityDao searchTemplateEntityDao;
    private final QueryInfoRetDao queryInfoRetDao;
    private final DepartmentEntityDao departmentEntityDao;
    private final OrganizationEntityDao organizationEntityDao;
    private final IPAddressEntityDao iPAddressEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchTemplateEntityDaoConfig = daoConfigMap.get(SearchTemplateEntityDao.class).clone();
        searchTemplateEntityDaoConfig.initIdentityScope(type);

        queryInfoRetDaoConfig = daoConfigMap.get(QueryInfoRetDao.class).clone();
        queryInfoRetDaoConfig.initIdentityScope(type);

        departmentEntityDaoConfig = daoConfigMap.get(DepartmentEntityDao.class).clone();
        departmentEntityDaoConfig.initIdentityScope(type);

        organizationEntityDaoConfig = daoConfigMap.get(OrganizationEntityDao.class).clone();
        organizationEntityDaoConfig.initIdentityScope(type);

        iPAddressEntityDaoConfig = daoConfigMap.get(IPAddressEntityDao.class).clone();
        iPAddressEntityDaoConfig.initIdentityScope(type);

        searchTemplateEntityDao = new SearchTemplateEntityDao(searchTemplateEntityDaoConfig, this);
        queryInfoRetDao = new QueryInfoRetDao(queryInfoRetDaoConfig, this);
        departmentEntityDao = new DepartmentEntityDao(departmentEntityDaoConfig, this);
        organizationEntityDao = new OrganizationEntityDao(organizationEntityDaoConfig, this);
        iPAddressEntityDao = new IPAddressEntityDao(iPAddressEntityDaoConfig, this);

        registerDao(SearchTemplateEntity.class, searchTemplateEntityDao);
        registerDao(QueryInfoRet.class, queryInfoRetDao);
        registerDao(DepartmentEntity.class, departmentEntityDao);
        registerDao(OrganizationEntity.class, organizationEntityDao);
        registerDao(IPAddressEntity.class, iPAddressEntityDao);
    }
    
    public void clear() {
        searchTemplateEntityDaoConfig.getIdentityScope().clear();
        queryInfoRetDaoConfig.getIdentityScope().clear();
        departmentEntityDaoConfig.getIdentityScope().clear();
        organizationEntityDaoConfig.getIdentityScope().clear();
        iPAddressEntityDaoConfig.getIdentityScope().clear();
    }

    public SearchTemplateEntityDao getSearchTemplateEntityDao() {
        return searchTemplateEntityDao;
    }

    public QueryInfoRetDao getQueryInfoRetDao() {
        return queryInfoRetDao;
    }

    public DepartmentEntityDao getDepartmentEntityDao() {
        return departmentEntityDao;
    }

    public OrganizationEntityDao getOrganizationEntityDao() {
        return organizationEntityDao;
    }

    public IPAddressEntityDao getIPAddressEntityDao() {
        return iPAddressEntityDao;
    }

}
