package com.example.administrator.mobilepacsviewer.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.administrator.mobilepacsviewer.model.SearchTemplateEntity;
import com.example.administrator.mobilepacsviewer.model.QueryInfoRet;
import com.example.administrator.mobilepacsviewer.model.DepartmentEntity;
import com.example.administrator.mobilepacsviewer.model.DicItemMstEntity;
import com.example.administrator.mobilepacsviewer.model.OrganizationEntity;

import com.example.administrator.mobilepacsviewer.model.SearchTemplateEntityDao;
import com.example.administrator.mobilepacsviewer.model.QueryInfoRetDao;
import com.example.administrator.mobilepacsviewer.model.DepartmentEntityDao;
import com.example.administrator.mobilepacsviewer.model.DicItemMstEntityDao;
import com.example.administrator.mobilepacsviewer.model.OrganizationEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchTemplateEntityDaoConfig;
    private final DaoConfig queryInfoRetDaoConfig;
    private final DaoConfig departmentEntityDaoConfig;
    private final DaoConfig dicItemMstEntityDaoConfig;
    private final DaoConfig organizationEntityDaoConfig;

    private final SearchTemplateEntityDao searchTemplateEntityDao;
    private final QueryInfoRetDao queryInfoRetDao;
    private final DepartmentEntityDao departmentEntityDao;
    private final DicItemMstEntityDao dicItemMstEntityDao;
    private final OrganizationEntityDao organizationEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchTemplateEntityDaoConfig = daoConfigMap.get(SearchTemplateEntityDao.class).clone();
        searchTemplateEntityDaoConfig.initIdentityScope(type);

        queryInfoRetDaoConfig = daoConfigMap.get(QueryInfoRetDao.class).clone();
        queryInfoRetDaoConfig.initIdentityScope(type);

        departmentEntityDaoConfig = daoConfigMap.get(DepartmentEntityDao.class).clone();
        departmentEntityDaoConfig.initIdentityScope(type);

        dicItemMstEntityDaoConfig = daoConfigMap.get(DicItemMstEntityDao.class).clone();
        dicItemMstEntityDaoConfig.initIdentityScope(type);

        organizationEntityDaoConfig = daoConfigMap.get(OrganizationEntityDao.class).clone();
        organizationEntityDaoConfig.initIdentityScope(type);

        searchTemplateEntityDao = new SearchTemplateEntityDao(searchTemplateEntityDaoConfig, this);
        queryInfoRetDao = new QueryInfoRetDao(queryInfoRetDaoConfig, this);
        departmentEntityDao = new DepartmentEntityDao(departmentEntityDaoConfig, this);
        dicItemMstEntityDao = new DicItemMstEntityDao(dicItemMstEntityDaoConfig, this);
        organizationEntityDao = new OrganizationEntityDao(organizationEntityDaoConfig, this);

        registerDao(SearchTemplateEntity.class, searchTemplateEntityDao);
        registerDao(QueryInfoRet.class, queryInfoRetDao);
        registerDao(DepartmentEntity.class, departmentEntityDao);
        registerDao(DicItemMstEntity.class, dicItemMstEntityDao);
        registerDao(OrganizationEntity.class, organizationEntityDao);
    }
    
    public void clear() {
        searchTemplateEntityDaoConfig.getIdentityScope().clear();
        queryInfoRetDaoConfig.getIdentityScope().clear();
        departmentEntityDaoConfig.getIdentityScope().clear();
        dicItemMstEntityDaoConfig.getIdentityScope().clear();
        organizationEntityDaoConfig.getIdentityScope().clear();
    }

    public SearchTemplateEntityDao getSearchTemplateEntityDao() {
        return searchTemplateEntityDao;
    }

    public QueryInfoRetDao getQueryInfoRetDao() {
        return queryInfoRetDao;
    }

    public DepartmentEntityDao getDepartmentEntityDao() {
        return departmentEntityDao;
    }

    public DicItemMstEntityDao getDicItemMstEntityDao() {
        return dicItemMstEntityDao;
    }

    public OrganizationEntityDao getOrganizationEntityDao() {
        return organizationEntityDao;
    }

}
