package com.example.administrator.mobilepacsviewer.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DEPARTMENT_ENTITY".
 */
public class DepartmentEntity {

    private Long id;
    /** Not-null value. */
    private String DeptName;

    public DepartmentEntity() {
    }

    public DepartmentEntity(Long id) {
        this.id = id;
    }

    public DepartmentEntity(Long id, String DeptName) {
        this.id = id;
        this.DeptName = DeptName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDeptName() {
        return DeptName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeptName(String DeptName) {
        this.DeptName = DeptName;
    }

}
