package com.example.administrator.mobilepacsviewer.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DIC_ITEM_MST_ENTITY".
 */
public class DicItemMstEntity {

    private Long id;
    private String ItemName;
    private String ItemRepresen;
    private String TypeCode;

    public DicItemMstEntity() {
    }

    public DicItemMstEntity(Long id) {
        this.id = id;
    }

    public DicItemMstEntity(Long id, String ItemName, String ItemRepresen, String TypeCode) {
        this.id = id;
        this.ItemName = ItemName;
        this.ItemRepresen = ItemRepresen;
        this.TypeCode = TypeCode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getItemName() {
        return ItemName;
    }

    public void setItemName(String ItemName) {
        this.ItemName = ItemName;
    }

    public String getItemRepresen() {
        return ItemRepresen;
    }

    public void setItemRepresen(String ItemRepresen) {
        this.ItemRepresen = ItemRepresen;
    }

    public String getTypeCode() {
        return TypeCode;
    }

    public void setTypeCode(String TypeCode) {
        this.TypeCode = TypeCode;
    }

}
