package com.example.administrator.mobilepacsviewer.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.administrator.mobilepacsviewer.model.IPAddressEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IPADDRESS_ENTITY".
*/
public class IPAddressEntityDao extends AbstractDao<IPAddressEntity, Long> {

    public static final String TABLENAME = "IPADDRESS_ENTITY";

    /**
     * Properties of entity IPAddressEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IPName = new Property(1, String.class, "IPName", false, "IPNAME");
        public final static Property IPLogInAddr = new Property(2, String.class, "IPLogInAddr", false, "IPLOG_IN_ADDR");
        public final static Property IPImageAddr = new Property(3, String.class, "IPImageAddr", false, "IPIMAGE_ADDR");
    };


    public IPAddressEntityDao(DaoConfig config) {
        super(config);
    }
    
    public IPAddressEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IPADDRESS_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IPNAME\" TEXT," + // 1: IPName
                "\"IPLOG_IN_ADDR\" TEXT," + // 2: IPLogInAddr
                "\"IPIMAGE_ADDR\" TEXT);"); // 3: IPImageAddr
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IPADDRESS_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, IPAddressEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String IPName = entity.getIPName();
        if (IPName != null) {
            stmt.bindString(2, IPName);
        }
 
        String IPLogInAddr = entity.getIPLogInAddr();
        if (IPLogInAddr != null) {
            stmt.bindString(3, IPLogInAddr);
        }
 
        String IPImageAddr = entity.getIPImageAddr();
        if (IPImageAddr != null) {
            stmt.bindString(4, IPImageAddr);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public IPAddressEntity readEntity(Cursor cursor, int offset) {
        IPAddressEntity entity = new IPAddressEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // IPName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // IPLogInAddr
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // IPImageAddr
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, IPAddressEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIPName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIPLogInAddr(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIPImageAddr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(IPAddressEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(IPAddressEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
