package com.example.administrator.mobilepacsviewer.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IPADDRESS_ENTITY".
 */
public class IPAddressEntity {

    private Long id;
    private String IPName;
    private String IPLogInAddr;
    private String IPImageAddr;

    public IPAddressEntity() {
    }

    public IPAddressEntity(Long id) {
        this.id = id;
    }

    public IPAddressEntity(Long id, String IPName, String IPLogInAddr, String IPImageAddr) {
        this.id = id;
        this.IPName = IPName;
        this.IPLogInAddr = IPLogInAddr;
        this.IPImageAddr = IPImageAddr;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIPName() {
        return IPName;
    }

    public void setIPName(String IPName) {
        this.IPName = IPName;
    }

    public String getIPLogInAddr() {
        return IPLogInAddr;
    }

    public void setIPLogInAddr(String IPLogInAddr) {
        this.IPLogInAddr = IPLogInAddr;
    }

    public String getIPImageAddr() {
        return IPImageAddr;
    }

    public void setIPImageAddr(String IPImageAddr) {
        this.IPImageAddr = IPImageAddr;
    }

}
