package com.example.administrator.mobilepacsviewer.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUERY_INFO_RET".
 */
public class QueryInfoRet {

    private Long id;
    private String AccessionNumber;
    private String Name;
    private String Sex;
    private String Age;
    private String AgeUnit;
    private String ServiceSectID;
    private String ServiceText;
    private String ObservationDate;
    private String MedRecNO;
    private String PatientClass;
    private String InPatientNO;
    private String OutPatientNO;
    private String PointOfCare;
    private String Bed;
    private String OrganizationID;
    private String RequestOrgName;
    private String RequestDeptName;
    private String ProviderName;
    private String RequestedDate;
    private String ProcedureName;
    private String ResultAssistantID;
    private String ResultAssistantName;
    private String ObservationUID;

    public QueryInfoRet() {
    }

    public QueryInfoRet(Long id) {
        this.id = id;
    }

    public QueryInfoRet(Long id, String AccessionNumber, String Name, String Sex, String Age, String AgeUnit, String ServiceSectID, String ServiceText, String ObservationDate, String MedRecNO, String PatientClass, String InPatientNO, String OutPatientNO, String PointOfCare, String Bed, String OrganizationID, String RequestOrgName, String RequestDeptName, String ProviderName, String RequestedDate, String ProcedureName, String ResultAssistantID, String ResultAssistantName, String ObservationUID) {
        this.id = id;
        this.AccessionNumber = AccessionNumber;
        this.Name = Name;
        this.Sex = Sex;
        this.Age = Age;
        this.AgeUnit = AgeUnit;
        this.ServiceSectID = ServiceSectID;
        this.ServiceText = ServiceText;
        this.ObservationDate = ObservationDate;
        this.MedRecNO = MedRecNO;
        this.PatientClass = PatientClass;
        this.InPatientNO = InPatientNO;
        this.OutPatientNO = OutPatientNO;
        this.PointOfCare = PointOfCare;
        this.Bed = Bed;
        this.OrganizationID = OrganizationID;
        this.RequestOrgName = RequestOrgName;
        this.RequestDeptName = RequestDeptName;
        this.ProviderName = ProviderName;
        this.RequestedDate = RequestedDate;
        this.ProcedureName = ProcedureName;
        this.ResultAssistantID = ResultAssistantID;
        this.ResultAssistantName = ResultAssistantName;
        this.ObservationUID = ObservationUID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccessionNumber() {
        return AccessionNumber;
    }

    public void setAccessionNumber(String AccessionNumber) {
        this.AccessionNumber = AccessionNumber;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getSex() {
        return Sex;
    }

    public void setSex(String Sex) {
        this.Sex = Sex;
    }

    public String getAge() {
        return Age;
    }

    public void setAge(String Age) {
        this.Age = Age;
    }

    public String getAgeUnit() {
        return AgeUnit;
    }

    public void setAgeUnit(String AgeUnit) {
        this.AgeUnit = AgeUnit;
    }

    public String getServiceSectID() {
        return ServiceSectID;
    }

    public void setServiceSectID(String ServiceSectID) {
        this.ServiceSectID = ServiceSectID;
    }

    public String getServiceText() {
        return ServiceText;
    }

    public void setServiceText(String ServiceText) {
        this.ServiceText = ServiceText;
    }

    public String getObservationDate() {
        return ObservationDate;
    }

    public void setObservationDate(String ObservationDate) {
        this.ObservationDate = ObservationDate;
    }

    public String getMedRecNO() {
        return MedRecNO;
    }

    public void setMedRecNO(String MedRecNO) {
        this.MedRecNO = MedRecNO;
    }

    public String getPatientClass() {
        return PatientClass;
    }

    public void setPatientClass(String PatientClass) {
        this.PatientClass = PatientClass;
    }

    public String getInPatientNO() {
        return InPatientNO;
    }

    public void setInPatientNO(String InPatientNO) {
        this.InPatientNO = InPatientNO;
    }

    public String getOutPatientNO() {
        return OutPatientNO;
    }

    public void setOutPatientNO(String OutPatientNO) {
        this.OutPatientNO = OutPatientNO;
    }

    public String getPointOfCare() {
        return PointOfCare;
    }

    public void setPointOfCare(String PointOfCare) {
        this.PointOfCare = PointOfCare;
    }

    public String getBed() {
        return Bed;
    }

    public void setBed(String Bed) {
        this.Bed = Bed;
    }

    public String getOrganizationID() {
        return OrganizationID;
    }

    public void setOrganizationID(String OrganizationID) {
        this.OrganizationID = OrganizationID;
    }

    public String getRequestOrgName() {
        return RequestOrgName;
    }

    public void setRequestOrgName(String RequestOrgName) {
        this.RequestOrgName = RequestOrgName;
    }

    public String getRequestDeptName() {
        return RequestDeptName;
    }

    public void setRequestDeptName(String RequestDeptName) {
        this.RequestDeptName = RequestDeptName;
    }

    public String getProviderName() {
        return ProviderName;
    }

    public void setProviderName(String ProviderName) {
        this.ProviderName = ProviderName;
    }

    public String getRequestedDate() {
        return RequestedDate;
    }

    public void setRequestedDate(String RequestedDate) {
        this.RequestedDate = RequestedDate;
    }

    public String getProcedureName() {
        return ProcedureName;
    }

    public void setProcedureName(String ProcedureName) {
        this.ProcedureName = ProcedureName;
    }

    public String getResultAssistantID() {
        return ResultAssistantID;
    }

    public void setResultAssistantID(String ResultAssistantID) {
        this.ResultAssistantID = ResultAssistantID;
    }

    public String getResultAssistantName() {
        return ResultAssistantName;
    }

    public void setResultAssistantName(String ResultAssistantName) {
        this.ResultAssistantName = ResultAssistantName;
    }

    public String getObservationUID() {
        return ObservationUID;
    }

    public void setObservationUID(String ObservationUID) {
        this.ObservationUID = ObservationUID;
    }

}
